---
- name: Shell Examples
  hosts: localhost
  connection: local
  collections:
    - community.dns
  tasks:
    - name: Check Date with Shell command
      shell:
         "date"
      register: datecmd
      tags: datecmd

    - name: Retrieve TXT values from all nameservers for two DNS names
      community.dns.nameserver_record_info:
        name:
          - www.example.com
          - example.org
        type: TXT
      register: result